
version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/arcjet/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/arcjet/pgadmin
    ports:
      - "8000:80"
    depends_on:
      - db


volumes:
  db-data:
  pgadmin-data: