CREATE TABLE IF NOT EXISTS products  (
	id SERIAL PRIMARY KEY,
	name VARCHAR (255) NOT NULL,
	image VARCHAR (255) NOT NULL,
	price DECIMAL (10, 2) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL UNIQUE

)


ALTER TABLE users ADD ROLE VARCHAR(10) DEFAULT "user";

